---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2
    driver:
      box: tas50/windows_2012r2
  - name: windows-2016
    driver_config:
      box: tas50/windows_2016
  - name: windows-2019
    driver_config:
      box: tas50/windows_2019
suites:
  - name: default
    run_list:
      - recipe[msys2::default]
    attributes:
      msys2:
        install_dir: "C:/msys64"
        packages: ["git"]
        override_package: true
        override_execute: true
