name 'msys2'
source_url       'https://www.github.com/sous-chefs/msys2'
issues_url       'https://www.github.com/sous-chefs/msys2/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures MSYS2'
version          '2.0.2'
chef_version     '>= 15.3'

supports 'windows'
