name 'msys2'
maintainer 'Brian Holtkamp'
maintainer_email 'brholtkamp@gmail.com'
license 'all_rights'
description 'Installs/Configures MSYS2'
long_description 'Installs/Configures MSYS2'
version '1.0.2'
source_url 'https://www.github.com/brholtkamp/msys2-cookbook'
issues_url 'https://www.github.com/brholtkamp/msys2-cookbook/issues'
